name: neirodev_test
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  auto_route: ^7.8.3
  bloc: ^8.1.2
  collection: ^1.17.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  injectable: ^2.3.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  rx_shared_preferences: ^3.0.0
  rxdart: ^0.27.7
  sliding_up_panel2: ^3.3.0+1
  snap_scroll_physics: ^0.0.1+3
  sticky_headers: ^0.3.0+2
  timeago: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  freezed: ^2.4.2
  injectable_generator: ^2.4.0
  json_serializable: ^6.7.1
  flutter_gen_runner: ^5.3.2

flutter_gen:
  output: lib/generated/
  
  integrations:
    flutter_svg: true

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik.ttf
        - asset: assets/fonts/Rubik600.ttf
          weight: 600
        - asset: assets/fonts/Rubik700.ttf
          weight: 700